### ISSUE TITLE
No such file or directory: './app/index.js'

### ISSUE THREAD

**Issue by EditFox** [justinoboyle/mydiscord#17]
upon opening mydiscord (i had python 3 way before this), it finds discordcanary as normal, goes to it's directory, and then spits this
`Found DiscordCanary.exe under C:\Users\Metro\AppData\Local\DiscordCanary\app-0.0.211
Traceback (most recent call last):
  File "c:\users\metro\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\metro\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Metro\Anaconda3\Scripts\mydiscord.exe\__main__.py", line 9, in <module>
  File "c:\users\metro\anaconda3\lib\site-packages\mydiscord\app.py", line 275, in main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'`

checking the file, it seems the most recent version of discord might have changed its filesystem?
index.js seems to now be located (relative to the code) in `./app/app_bootstrap/index.js`

**Comment by cyyynthia** [comment]
Discord did a lot of change to its file structure since last mydiscord update (1 yr ago). Also, this project looks like abandonned and is no longer maintened. You should move to [DiscordInjections](https://github.com/DiscordInjections/DiscordInjections) if you want to add some js or use [BeautifulDiscord](https://github.com/leovoel/BeautifulDiscord) if you just want to inject CSS

**Comment by justinoboyle** [comment]
Apologizes for the late response. Yes, move to DiscordInjections. Closed
